# Generated by Django 3.1 on 2021-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsummary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Secretary'), (2, 'Manager'), (3, 'Staff')], null=True),
        ),
    ]
