# Generated by Django 3.2 on 2021-11-13 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsummary', '0002_auto_20211106_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='room_id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsummary.room'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('recieve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobsummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('document', models.CharField(max_length=255)),
                ('deadline_plan', models.DateField()),
                ('deadline', models.DateField()),
                ('status', models.SmallIntegerField(choices=[(0, 'NotSent'), (1, 'Pending'), (2, 'Approved')], null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobsummary.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
