# Generated by Django 3.2 on 2021-12-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsummary', '0005_myuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsummary',
            name='upload_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
