# Generated by Django 3.1 on 2021-12-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsummary', '0006_jobsummary_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsummary',
            name='assign',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
