# Generated by Django 3.1 on 2021-12-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsummary', '0008_auto_20211222_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsummary',
            options={'permissions': (('can_assign_job', 'Can assign job'), ('can_receive_job', 'Can receive Job'))},
        ),
    ]
