# Generated by Django 3.1 on 2021-12-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsummary', '0009_auto_20211222_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsummary',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Assigned'), (3, 'Finished')], null=True),
        ),
    ]
