# Generated by Django 3.1 on 2022-01-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsummary', '0010_auto_20211225_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsummary',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobsummary',
            name='deadline_plan',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobsummary',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Assigned'), (2, 'Finished')], null=True),
        ),
    ]
